#BoardConfig.mk by IceMan

LOCAL_PATH := device/Ulefone/Power_Armor14_Pro

# type (yes if MTK - no if other)
MEDIATEK_TYPE := yes

# support 64bit (yes if 64bit - no if 32bit)
MTK_K64_SUPPORT := yes

# Platform
TARGET_BOOTLOADER_BOARD_NAME := mt6768
TARGET_BOARD_PLATFORM := mt6768

# Architecture
ifneq ($(MTK_K64_SUPPORT),yes)
ARCH := arm
TARGET_ARCH := arm
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_VARIANT := cortex-a53
else
ARCH := arm64
TARGET_ARCH := arm64
TARGET_NO_BOOTLOADER := true
TARGET_CPU_ABI := arm64-v8a
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_CORTEX_A53 := true
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI),$(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
endif

TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
ARCH_ARM_HAVE_NEON := true
ARCH_ARM_HAVE_VFP := true
TARGET_GLOBAL_CFLAGS   += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/kernel

# Partitions & Kernel

BOARD_FLASH_BLOCK_SIZE :=	131072
BOARD_BOOTIMAGE_PARTITION_SIZE :=_a	33554432
vendor_BOARD_BOOTIMAGE_PARTITION_SIZE :=_a	67108864
BOARD_BOOTIMAGE_PARTITION_SIZE :=_para	27262976
BOARD_BOOTIMAGE_PARTITION_SIZE :=_b	33554432
vendor_BOARD_BOOTIMAGE_PARTITION_SIZE :=_b	67108864
vbmeta_BOARD_SYSTEMIMAGE_PARTITION_SIZE :=_a	8388608
vbmeta_BOARD_SYSTEMIMAGE_PARTITION_SIZE :=_b	8388608
BOARD_USERDATAIMAGE_PARTITION_SIZE :=	3221225472
BOARD_PROTECT1IMAGE_PARTITION_SIZE :=	8388608
BOARD_PROTECT2IMAGE_PARTITION_SIZE :=	8773632
BOARD_KERNEL_CMDLINE := 'bootopt=64S3,32N2,64N2buildvariant=user'
BOARD_KERNEL_PAGESIZE := 2048	
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x07c08000
BOARD_TAGS_OFFSET := 0x0bc08000
BOARD_KERNEL_BASE := 0x40078000

BOARD_MKBOOTIMG_ARGS := --kernel_offset $(BOARD_KERNEL_OFFSET) --ramdisk_offset $(BOARD_RAMDISK_OFFSET) --tags_offset $(BOARD_TAGS_OFFSET) --base $(BOARD_KERNEL_BASE) --cmdline "$(BOARD_KERNEL_CMDLINE)"
TARGET_KMODULES := true

# Other Partition
BLOCK_BASED_OTA := false
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_KERNEL_HAVE_EXFAT := true
TARGET_KERNEL_HAVE_NTFS := true
TARGET_KERNEL_HAVE_F2FS := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

#Mediatek flags
ifneq ($(MEDIATEK_TYPE),yes)
BOARD_CUSTOM_BOOTIMG := false
else
BOARD_CUSTOM_BOOTIMG := true
BOARD_CUSTOM_BOOTIMG_MK := $(LOCAL_PATH)/mkmtkbootimg.mk
endif

# TWRP recovery
RECOVERY_VARIANT := twrp
TWHAVE_SELINUX := false
TW_INCLUDE_CRYPTO := true
TW_NO_USB_STORAGE := false
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_USE_TOOLBOX := false
RECOVERY_SDCARD_ON_DATA := true
TW_THEME := portrait_hdpi
TW_DEFAULT_EXTERNAL_STORAGE := true
#TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/mt_usb/musb-hdrc.0/gadget/lun%d/file"
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"

# View button bootloader
TW_NO_REBOOT_BOOTLOADER := false
# View button downloadmode - true only samsung
TW_HAS_DOWNLOAD_MODE := false

# Default Brightness (TW_DEFAULT_BRIGHTNESS=255-->100%; TW_DEFAULT_BRIGHTNESS=218-->85%)
TW_DEFAULT_BRIGHTNESS := 255
TW_MAX_BRIGHTNESS := 255

# MTK Hardware
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_USES_LEGACY_MTK_AV_BLOB := true
COMMON_GLOBAL_CFLAGS += -DMTK_HARDWARE  -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
COMMON_GLOBAL_CPPFLAGS += -DMTK_HARDWARE  -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL

# Flags
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD
COMMON_GLOBAL_CFLAGS += -DDISABLE_HW_ID_MATCH_CHECK
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true

# Use ro.product.model
TW_USE_MODEL_HARDWARE_ID_FOR_DEVICE_ID := true

# Exfat support
TW_NO_EXFAT := false
TW_NO_EXFAT_FUSE := false

# Internal storage
TW_INTERNAL_STORAGE_PATH := "/data/media"
TW_INTERNAL_STORAGE_MOUNT_POINT := "data"

# External storage
TW_EXTERNAL_STORAGE_PATH := "/external_sd"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "external_sd"

# Name device MTP
TW_MTP_DEVICE := "/dev/mtp_usb"

# Set language default
TW_DEFAULT_LANGUAGE := en

ifneq ($(MTK_K64_SUPPORT),yes)
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.zygote=zygote32
else
PRODUCT_COPY_FILES += system/core/rootdir/init.zygote64_32.rc:root/init.zygote64_32.rc
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += ro.zygote=zygote64_32
endif

# For Version TWRP
TW_SPECIFIC_VERSION_STR := "3.0.2-2 by IceMan"

# For time Zone Italy
TW_SPECIFIC_TIME_ZONE_VAR := "EST5EDT,M3.2.0,M11.1.0"
TW_SPECIFIC_TIME_ZONE_GUISEL := "EST5;EDT,M3.2.0,M11.1.0"

# For H24 hours
TW_SPECIFIC_MILITARY_TIME := "1"

# For Screen_timeout_secs
TW_SCREEN_TIMEOUT_SECS := "120"